### ISSUE TITLE
Incompatible with S3 backend

### ISSUE THREAD

**Issue by jgsuess** [ansible-collections/cloud.terraform#100]
##### SUMMARY
When using the cloud.terraform.terraform_provider on an example that uses aws backend s3, the inventory is empty.

I have the ansible terraform provider to add hosts to the terraform state. I verified that the hosts are part of the state as they show in the state file on S3. I wanted to export these hosts as an ansible inventory and used the cloud.terraform.terraform_provider_inventory for this purpose. The provider fails to perform this task, and gave me an empty inventory listing. This is despite the fact that `terraform show` shows the content correctly.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

https://github.com/ansible-collections/cloud.terraform/blob/main/docs/cloud.terraform.terraform_provider_inventory.rst
https://registry.terraform.io/providers/ansible/ansible/latest
https://developer.hashicorp.com/terraform/language/settings/backends/s3

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/jg/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by gravesm** [comment]
This is fixed in #55.
