### ISSUE TITLE
version 3.0.0 does not have `Release`

### ISSUE THREAD

**Issue by akira6592** [ansible-collections/cloud.terraform#147]
##### SUMMARY

The collection version 3.0.0 has released, but does not have [Release](https://github.com/ansible-collections/cloud.terraform/releases).

This could mislead visitors to this repository into thinking that 3.0.0 has not yet been released.

**Comment by abikouo** [comment]
@akira6592 [v3.0.0](https://github.com/ansible-collections/cloud.terraform/releases/tag/3.0.0) created.

**Comment by akira6592** [comment]
@abikouo Thank you!
