### ISSUE TITLE
Terraform Module doc links go to 404

### ISSUE THREAD

**Issue by vap0rtranz** [ansible-collections/cloud.terraform#21]
##### SUMMARY
Terraform Module doc links go to 404

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
[doc link](https://github.com/ansible-collections/cloud.terraform/blob/main/docs/cloud.terraform.terraform_module.rst)

**Comment by vap0rtranz** [comment]
[doc link](https://github.com/ansible-collections/cloud.terraform/blob/main/docs/cloud.terraform.terraform_module.rst)

**Comment by tima** [comment]
Thanks for filing this. It isn't clear where you found this 404 link. Could you be more specific?

**Comment by vap0rtranz** [comment]
Sure.  The main README, under Modules section, in the table, the 2 links there.

Direct link to the table:

https://github.com/ansible-collections/cloud.terraform#modules

**Comment by tima** [comment]
OK I see it now. Thanks @vap0rtranz. It looks like the embedded docs in the modules where extracted into their own files. We'll get that sorted shortly.

**Comment by sstanovnik** [comment]
Resolved by #23. Thank you for the report!
