### ISSUE TITLE
bug: could not find imported module support code

### ISSUE THREAD

**Issue by sean-freeman** [ansible-collections/cloud.terraform#25]
##### SUMMARY

Ansible Playbook could not find imported module support code when using v1.0.1 from `main` branch of cloud.terraform Ansible Collection

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
[:~] $ ansible --version
ansible [core 2.11.12] 
  python version = 3.7.8 (default, Oct 25 2020, 11:34:54) [Clang 12.0.0 (clang-1200.0.32.21)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
1.0.1 from GitHub Repo main branch
```

##### OS / ENVIRONMENT

```
macOS 13.1
```

##### STEPS TO REPRODUCE

```yaml
collections:
  - name: https://github.com/ansible-collections/cloud.terraform.git
    type: git
    version: main
```
`ansible-galaxy collection install --requirements-file ./ansible_requirements_collections.yml`

##### EXPECTED RESULTS

```
Normal execution of terraform Ansible Module from cloud.terraform Ansible Collection
```

##### ACTUAL RESULTS
```yaml
FAILED! =>
{
    "msg": 
    "Could not find imported module support code for
    ansible_collections.cloud.terraform.plugins.modules.terraform.
    Looked for (
      [
        'ansible.module_utils.compat.version.LooseVersion',
        'ansible.module_utils.compat.version'
      ]
    )"
}
```

**Comment by PolonaM** [comment]
@sean-freeman The problem is in your ansible version, which doesn't support the imports. The solution is to update the ansible version (and python version) as instructed in the readme: https://github.com/ansible-collections/cloud.terraform/blob/main/README.md

**Comment by sean-freeman** [comment]
@PolonaM Please explain why installation from Ansible Galaxy was successful then. Did dependency version requirements change for Collection 1.0.1 ?

**Comment by sstanovnik** [comment]
The requirements have been in place from the initial version of the collection. Ansible unfortunately doesn't verify the content of `runtime/meta.yml:requires_ansible` when installing either from Galaxy or locally and allows you to install whatever you specify. See https://github.com/ansible/ansible/issues/78539 for more details.

**Comment by sean-freeman** [comment]
Confirmed referenced Ansible bug is accurate:
- on Ansible Core 2.11.x I was able to install the Ansible Collection from Ansible Galaxy (bug), and not able to install from the Git Repo
- on Ansible Core 2.13.x I was able to install the Ansible Collection from Ansible Galaxy or the Git Repo [see below confirmation output]

However, @PolonaM please note the below output shows that when installing from the Git Repo `main` branch (release `1.0.1`) -- the Ansible Core 2.13.x output lists the version as `1.0.0` still. This may also be a reason why there is no Ansible Galaxy `1.0.1` entry triggered? It would be the metadata file at fault:
https://github.com/ansible-collections/cloud.terraform/blob/main/galaxy.yml#L5


### Confirmation output

```shell
[:Desktop] $ ansible --version
ansible [core 2.13.4]
  config file = None
  python version = 3.9.6 (default, Sep  1 2021, 09:17:26) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.1.2
  libyaml = True

[:Desktop] $ ansible-galaxy collection install --requirements-file ./ansible_requirements_collections.yml
Starting galaxy collection install process
Process install dependency map
Cloning into '/Users/USER_NAME/.ansible/tmp/ansible-local-22104f102o9gt/tmpt1r4fqia/cloud.terraformk6827oi7'...
remote: Enumerating objects: 1190, done.
remote: Counting objects: 100% (399/399), done.
remote: Compressing objects: 100% (220/220), done.
remote: Total 1190 (delta 156), reused 345 (delta 131), pack-reused 791
Receiving objects: 100% (1190/1190), 260.55 KiB | 4.27 MiB/s, done.
Resolving deltas: 100% (368/368), done.
Already on 'main'
Your branch is up to date with 'origin/main'.
Starting collection install process
Installing 'cloud.terraform:1.0.0' to '/Users/USER_NAME/.ansible/collections/ansible_collections/cloud/terraform'
Created collection for cloud.terraform:1.0.0 at /Users/USER_NAME/.ansible/collections/ansible_collections/cloud/terraform
cloud.terraform:1.0.0 was installed successfully
```

**Comment by PolonaM** [comment]
@sean-freeman Thanks for the feedback! However main branch is always under construction, thus galaxy.yml not having "the right" version. If installing from git repo, you should install from "release" branches eg.: ansible-galaxy collection install git+https://github.com/ansible-collections/cloud.terraform.git,release_1.0.1.  And although release 1.0.1 exists in the repo, there really is no 1.0.1 release on Galaxy.
