### ISSUE TITLE
Version 1.0.1 is missing from the change log.

### ISSUE THREAD

**Issue by tima** [ansible-collections/cloud.terraform#38]
##### SUMMARY

From what I can see, the release of 1.0.1 that went into Automation Hub did not make it into the change log. 

Relates to #36 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

changelogs/

**Comment by jillr** [comment]
As 1.1.0 has now been released and is the most recent stable-1 release we are going to close this.
