### ISSUE TITLE
docs: inventory_from_outputs Ansible Role sample Terraform Output declarations

### ISSUE THREAD

**Issue by sean-freeman** [ansible-collections/cloud.terraform#40]
##### SUMMARY
inventory_from_outputs Ansible Role sample Terraform Output declarations are missing, therefore it is very difficult for first-time usage of this Ansible Role

The following should be provided in the documentation:
```hcl
output "terraform_var_host_list" {
  value = ????
}

output "terraform_var_name" {
  value = ????
}

output "terraform_var_ip" {
  value = ????
}

output "terraform_var_user" {
  value = ????
}

output "terraform_var_group" {
  value = ????
}
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
`/roles/inventory_from_outputs/README.md`

**Comment by sstanovnik** [comment]
Thank you for noticing and reporting this omission. We'll get an example included in the docs!

In the meantime, there is an integration test with an example at `tests/integration/targets/test_inventory_from_outputs/`, but I agree that that is not the best place for documentation.

**Comment by sean-freeman** [comment]
@PolonaM Also, the example playbook has an `s` on the `host_list` which causes an error.

```yaml
mapping_variables:
  host_lists:
```

Should be:

```yaml
mapping_variables:
  host_list:
```

**Comment by PolonaM** [comment]
@sean-freeman Thanks for noticing. I will update the readme
