### ISSUE TITLE
`child_modules` support

### ISSUE THREAD

**Issue by anthonyra** [ansible-collections/cloud.terraform#53]
##### SUMMARY

When the Terraform project uses modules the resulting `terraform show -json` has a different structure than currently expected.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

New `models.py`

Add a check in `TerraformRootModule` to see if `child_modules` exist if so utilize the `TerraformChildModules` definition.

##### ADDITIONAL INFORMATION

This would add module support for Terraform projects. Without this feature, projects that utilize modules will not be able to use `cloud.terraform` plugin for Ansible specifically the inventory plugin.

Expected
```json
"root_module": {
     "resources": [
          {...}
     ]
}
```
Actual
```json
"root_module": {
     "child_modules": [
          {
               "address": "module.name",
               "resources": [
                    {...}
                ]
         }
     ]
}
```

**Comment by ErikVenema** [comment]
I believe there is already a pull request open for this issue: #51

**Comment by dronenb** [comment]
PR #55 has already been merged and addresses this (amongst other things), so I think it should be available once the next version of this collection is released.
