### ISSUE TITLE
Plugin cloud.terraform.terraform_provider - backend_config support

### ISSUE THREAD

**Issue by MonolithProjects** [ansible-collections/cloud.terraform#74]
##### SUMMARY

Inventory plugin `cloud.terraform.terraform_provider` does support only local Terraform state file. It would be nice to have an option to use Terraform state stored in remote backend like S3.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

cloud.terraform.terraform_provider

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by thorsteinbn** [comment]
Until there is implicit support for remote state when no statefile is defined, you can get the same behavior by defining state_file as an empty string in your inventory.yml file. 

`
---
plugin: cloud.terraform.terraform_provider
state_file: ""
...
`

**Comment by MonolithProjects** [comment]
Hi @thorsteinbn, thanks! This works exactly how i need. I am closing this issue.
