### ISSUE TITLE
[cloud.terraform.terraform] Unable to define location of plan file

### ISSUE THREAD

**Issue by sfhl** [ansible-collections/cloud.terraform#87]
##### SUMMARY
When `state: planned` is deprecated and instead it is recommended to use `check_mode` in combination with `state: present` how may i define a plan file?
I would like to avoid using `/tmp`-directory

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cloud.terraform.terraform

##### ANSIBLE VERSION
```
2.14.3
```

##### COLLECTION VERSION
-->
```
1.1.1
```

##### EXPECTED RESULTS
I am able to define a location for the plan file as in `state: planned` mode.

##### ACTUAL RESULTS
I am not able to define a location for the plan file as in `state: planned` mode.

**Comment by rafaelpirolla** [comment]
check_mode doesn't exist in current cloud.terraform.terraform version 4.0.0.
Can you please reopen this issue?

**Comment by gravesm** [comment]
@rafaelpirolla It seems to work fine for me. Please open a new ticket with an example playbook to reproduce your problem.

**Comment by rafaelpirolla** [comment]
@gravesm maybe it's just a documentation question?
Here: https://github.com/ansible-collections/cloud.terraform/blob/main/docs/cloud.terraform.terraform_module.rst

In the "plan_file":
```
The path to a Terraform plan file to apply or generate.
When 'check_mode' is set to True or state=planned, a Terraform plan file will be generated and saved into the specified location.
When 'check_mode' is set to False and state is set to either present or absent, The existing Terraform plan file will be applied.
```

But the only option that look like this is the `check_destroy` one. Is that the case?

**Comment by gravesm** [comment]
https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_checkmode.html#using-check-mode

**Comment by rafaelpirolla** [comment]
Ok, facepalm. Never saw this before, thanks!
