### ISSUE TITLE
Remote state credentials as plugin arguments

### ISSUE THREAD

**Issue by aleprovencio** [ansible-collections/cloud.terraform#92]
##### SUMMARY
It would be nice if we could configure terraform's remote state credentials as plugin arguments, instead of using environment variables.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cloud.terraform.terraform_provider

##### ADDITIONAL INFORMATION
My idea is to have something like `amazon.aws.aws_ec2` [plugin](https://docs.ansible.com/ansible/latest/collections/amazon/aws/docsite/aws_ec2_guide.html)

IMO this approach is better because we can use `ansible-vault` for that.

**Comment by aleprovencio** [comment]
It looks like it does! :rocket: 
Thanks for the heads up !

**Comment by akira6592** [comment]
Your welcome!
